// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRCrazy_Core","status":true,"description":"v1.1.2 Required for most SRCrazy scripts. Provides some additional functions to standard classes.\n<SRCrazy_Core>","parameters":{"Cache Event Commands":"true"}},
{"name":"SRCrazy_EventIndicators","status":true,"description":"v0.3.1 Displays indicators above events\n<SRCrazy_EventIndicators>","parameters":{"Disabled At Start":"false","-- Icon Settings --":"","Icon Filename":"IconSet","Icon File Path":"system","Icon Width":"32","Icon Height":"32","-- Display Settings --":"","Y Offset":"-38","Opacity":"255","Layer Order":"5","Scale":"1","Hue":"0","-- Tween Settings --":"","Tween Position X":"false 0 0 1","Tween Position Y":"false 0 0 1","Tween Scale X":"false 0 0 1","Tween Scale Y":"false 0 0 1","Tween Opacity":"false 0 0 1","Tween Layer Order":"false 0 0 1","Tween Hue":"false 0 0 1"}},
{"name":"ScreenResolution","status":false,"description":"v1.00 Change your game's screen resolution to your liking!","parameters":{"Screen Width":"840","Screen Height":"1280"}},
{"name":"YEP_ExternalLinks","status":true,"description":"v1.01 Link back to your home page through the title screen\r\nand also be able to link your players from within the game.","parameters":{"Home Page URL":"https://www.youtube.com/","Home Page Text":"Tutorial","Popup Blocker Notice":"The link was blocked by a pop-up blocker."}}
];
